-- Chay file nay trong Supabase SQL Editor neu database chi giu dung 11 bang:
-- categories, items, combos, customers, orders, invoices, payments, promotions, roles, tables, users.
-- File chi them cot/index can cho code, KHONG tao cac bang phu orderdetails/comboitems/customerpromotions.

do $$ begin create type "Role" as enum ('CUSTOMER', 'STAFF', 'ADMIN'); exception when duplicate_object then null; end $$;
do $$ begin create type "TableStatus" as enum ('EMPTY', 'OCCUPIED', 'REQUESTING_BILL'); exception when duplicate_object then null; end $$;
do $$ begin create type "OrderStatus" as enum ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type "DiscountType" as enum ('PERCENTAGE', 'FIXED'); exception when duplicate_object then null; end $$;
do $$ begin create type "InvoiceStatus" as enum ('UNPAID', 'PAID', 'CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type "PaymentStatus" as enum ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'); exception when duplicate_object then null; end $$;
do $$ begin create type "PaymentMethod" as enum ('CASH', 'BANK_TRANSFER', 'CARD', 'E_WALLET'); exception when duplicate_object then null; end $$;

alter table users
  add column if not exists username text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists password text,
  add column if not exists role "Role" not null default 'CUSTOMER',
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "lastLoginAt" timestamptz,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table customers
  add column if not exists "userId" text,
  add column if not exists "fullName" text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists address text,
  add column if not exists city text,
  add column if not exists district text,
  add column if not exists "dateOfBirth" timestamptz,
  add column if not exists "customerType" text not null default 'GUEST',
  add column if not exists "loyaltyPoints" integer not null default 0,
  add column if not exists "totalSpent" double precision not null default 0,
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table categories
  add column if not exists "categoryName" text,
  add column if not exists description text,
  add column if not exists image text,
  add column if not exists "sortOrder" integer not null default 0,
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table items
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists price double precision not null default 0,
  add column if not exists image text,
  add column if not exists "categoryId" text,
  add column if not exists "isAvailable" boolean not null default true,
  add column if not exists "sortOrder" integer not null default 0,
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table combos
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists price double precision not null default 0,
  add column if not exists image text,
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table tables
  add column if not exists "tableNumber" text,
  add column if not exists capacity integer not null default 2,
  add column if not exists status "TableStatus" not null default 'EMPTY',
  add column if not exists "isActive" boolean not null default true,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table orders
  add column if not exists "orderNumber" integer generated by default as identity,
  add column if not exists "tableId" text,
  add column if not exists "userId" text,
  add column if not exists "customerId" text,
  add column if not exists "orderStatus" "OrderStatus" not null default 'PENDING',
  add column if not exists "subTotal" double precision not null default 0,
  add column if not exists "taxAmount" double precision not null default 0,
  add column if not exists "serviceCharge" double precision not null default 0,
  add column if not exists "discountAmount" double precision not null default 0,
  add column if not exists "totalAmount" double precision not null default 0,
  add column if not exists "promoCode" text,
  add column if not exists "customerNotes" text,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table invoices
  add column if not exists "invoiceNumber" text,
  add column if not exists "orderId" text,
  add column if not exists "customerId" text,
  add column if not exists "tableId" text,
  add column if not exists "subTotal" double precision not null default 0,
  add column if not exists "customerName" text,
  add column if not exists "customerTaxCode" text,
  add column if not exists "taxAmount" double precision not null default 0,
  add column if not exists discount double precision not null default 0,
  add column if not exists "totalAmount" double precision not null default 0,
  add column if not exists "paymentMethod" "PaymentMethod",
  add column if not exists status "InvoiceStatus" not null default 'UNPAID',
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now(),
  add column if not exists "paidAt" timestamptz,
  add column if not exists note text;

alter table payments
  add column if not exists "invoiceId" text,
  add column if not exists "orderId" text,
  add column if not exists "paymentMethod" "PaymentMethod" not null default 'CASH',
  add column if not exists amount double precision not null default 0,
  add column if not exists "paidAmount" double precision not null default 0,
  add column if not exists "changeAmount" double precision not null default 0,
  add column if not exists "paymentStatus" "PaymentStatus" not null default 'PENDING',
  add column if not exists "paidAt" timestamptz,
  add column if not exists "transactionCode" text,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

alter table promotions
  add column if not exists name text,
  add column if not exists code text,
  add column if not exists type "DiscountType" not null default 'PERCENTAGE',
  add column if not exists value double precision not null default 0,
  add column if not exists "minOrderAmount" double precision not null default 0,
  add column if not exists "maxDiscount" double precision,
  add column if not exists "usageLimit" integer,
  add column if not exists "usedCount" integer not null default 0,
  add column if not exists "startDate" timestamptz not null default now(),
  add column if not exists "endDate" timestamptz not null default (now() + interval '1 year'),
  add column if not exists "isActive" boolean not null default true,
  add column if not exists description text,
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists "updatedAt" timestamptz not null default now();

create unique index if not exists users_phone_unique on users(phone);
create unique index if not exists tables_table_number_unique on tables("tableNumber");
create unique index if not exists orders_order_number_unique on orders("orderNumber");
create unique index if not exists invoices_invoice_number_unique on invoices("invoiceNumber");
create unique index if not exists invoices_order_id_unique on invoices("orderId");
create unique index if not exists promotions_code_unique on promotions(code);
