-- Le Monde Steak official menu seed/update
-- Source: https://www.lemondesteak.com.vn/
-- Run this in Supabase SQL Editor after the main schema file.

insert into "categories" ("id","name","desc","sortOrder","isActive") values
  ('cat_petit',    'Les Classiques',      'Các phần steak cổ điển với thăn bò phi lê, khoai nghiền và sốt kiểu Pháp', 1, true),
  ('cat_codien',   'Gu Steak Cổ Điển',    'Hương vị Pháp kinh điển, đậm chất bistro truyền thống', 2, true),
  ('cat_dongvui',  'Steak À Deux',        'Phần steak định lượng lớn, ăn cùng nhiều gu sốt để chia sẻ cả bàn', 3, true),
  ('cat_sangtao',  'Gu Steak Sáng Tạo',   'Hương vị khác biệt từ sự pha trộn Á - Âu', 4, true),
  ('cat_pasta',    'Pasta',               'Mỳ Ý với các loại sốt đặc trưng', 5, true),
  ('cat_pizza',    'Pizza',               'Pizza dùng chung cho bữa ăn nhóm', 6, true),
  ('cat_salad',    'Salad',               'Salad và món tươi nhẹ', 7, true),
  ('cat_sides',    'Rau Củ Áp Chảo',      'Món phụ ăn kèm steak', 8, true),
  ('cat_do_chien', 'Đồ Chiên',            'Món chiên và combo cho trẻ em', 9, true)
on conflict ("id") do update set
  "name" = excluded."name",
  "desc" = excluded."desc",
  "sortOrder" = excluded."sortOrder",
  "isActive" = excluded."isActive";

insert into "items" ("id","name","price","categoryId","description","image","isActive") values
  ('item_rossini', 'Rossini', 299000, 'cat_petit',
   'Thăn bò phi lê ăn cùng gan ngỗng béo Pháp, khoai nghiền và sốt rượu vang Burgundy.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577603/rossini_g9knjo.png', true),
  ('item_suftturf', 'Surf & Turf', 279000, 'cat_petit',
   'Thăn bò phi lê ăn cùng tôm áp chảo, măng tây, khoai nghiền và sốt tiêu Phú Quốc.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577603/suft_turf_iqvw5o.png', true),
  ('item_petitclas', 'Petit Classique', 229000, 'cat_petit',
   'Thăn bò phi lê ăn cùng măng tây, khoai nghiền và sốt tùy chọn.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577600/petitclassique_w5svmv.png', true),

  ('item_frite', 'Steak & Frite', 249000, 'cat_codien',
   'Steak thăn ngoại 180g sốt tiêu Phú Quốc ăn kèm khoai tây chiên.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577594/steak_frite_w7w63d.png', true),
  ('item_saumon', 'Saumon Steak', 229000, 'cat_codien',
   'Steak cá hồi sốt hải sản miền Nam nước Pháp ăn kèm măng tây.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577593/saumonsteak_di8kv5.png', true),
  ('item_debistro', 'Steak De Bistro', 239000, 'cat_codien',
   'Bò áp chảo sốt tự chọn ăn kèm rau củ theo mùa và khoai nghiền hoặc khoai chiên.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577598/steakdebistro_ewvtlh.png', true),
  ('item_aupoivre', 'Steak Au Poivre', 279000, 'cat_codien',
   'Thăn ngoại 180g áp chảo phủ tiêu xanh Phú Quốc, ăn kèm măng tây và khoai bỏ lò.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577597/steakaupoirve_hy2fcd.png', true),
  ('item_vinrouge', 'Steak Au Vin Rouge', 259000, 'cat_codien',
   'Steak thăn ngoại 180g sốt rượu vang đỏ, ăn kèm khoai nghiền và hành caramélisé.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577597/steakauvinrouge_oztkxi.png', true),
  ('item_diane', 'Steak Diane', 279000, 'cat_codien',
   'Thăn ngoại 180g sốt Diane nấu từ nấm Porcini, nấm mỡ tươi và rượu Cognac, ăn kèm măng tây áp chảo.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577601/steakdiane_ojqbzq.png', true),

  ('item_thanngoai', 'Steak Thăn Ngoại Bò 360g', 449000, 'cat_dongvui',
   'Steak thăn ngoại bò 360g sốt tự chọn, ăn kèm đồ chiên và rau củ nướng theo mùa.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577592/steakthanngoaibo_vcjjt1.png', true),
  ('item_cahoi_dv', 'Steak Thăn Ngoại Bò & Cá Hồi', 399000, 'cat_dongvui',
   'Thăn ngoại bò 180g và cá hồi 150g sốt tự chọn, ăn kèm đồ chiên và rau củ nướng theo mùa.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577587/steakthanngoaibo_cahoi_cy9mga.png', true),
  ('item_heocotlet', 'Steak Thăn Ngoại Bò & Heo Cốt Lết', 379000, 'cat_dongvui',
   'Thăn ngoại bò 180g và heo cốt lết 220g sốt tự chọn, ăn kèm đồ chiên và rau củ nướng theo mùa.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577589/steakthanngoaibo_heocotlet_rjuym2.png', true),
  ('item_thanngoaiwg', 'Steak Thăn Ngoại Bò & Má Đùi Gà', 349000, 'cat_dongvui',
   'Thăn ngoại bò 180g và má đùi gà 180g ăn cùng khoai chiên, rau củ nướng theo mùa.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577590/steakthanngoaibo_maduiga_ybyv3j.png', true),
  ('item_heowagyu', 'Steak Heo Cốt Lết & Má Đùi Gà', 249000, 'cat_dongvui',
   'Heo cốt lết và má đùi gà ăn kèm đồ chiên, rau củ nướng theo mùa và sốt tự chọn.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577586/steakheocotlet_maduiga_jagjgd.png', true),

  ('item_wagyunam', 'Steak Má Đùi Gà & Nấm Mỡ Áp Chảo', 149000, 'cat_sangtao',
   'Má đùi gà 180g, nấm mỡ áp chảo, khoai nghiền và sốt nấm thông Pháp.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577578/steakmaduiga_nammoapchao_c0psid.png', true),
  ('item_luonvit', 'Steak Lườn Vịt', 179000, 'cat_sangtao',
   'Lườn vịt 200g ăn cùng khoai nghiền, hành caramélisé và sốt rượu vang.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577577/steakluonvit_qs155y.png', true),
  ('item_cahoi_st', 'Steak Cá Hồi & Cơm Bơ', 199000, 'cat_sangtao',
   'Cá hồi 150g ăn cùng cơm bơ, trứng chiên kiểu Pháp, rau củ theo mùa và sốt Teri.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577575/steakcahoi_ikyyud.png', true),
  ('item_cadory', 'Steak Cá Dory & Pasta', 139000, 'cat_sangtao',
   'Cá Dory 200g ăn cùng pasta và sốt hải sản miền Nam nước Pháp.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577572/steakcadory_ntmsy4.png', true),
  ('item_suoncotlet', 'Steak Sườn Cốt Lết Sốt Tiêu Phú Quốc', 179000, 'cat_sangtao',
   'Sườn cốt lết 220g ăn cùng khoai chiên và sốt tiêu Phú Quốc.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577581/steaksuoncotletsottieuphuquoc_y4xu0h.png', true),
  ('item_mini_teriyaki', 'Steak Mini Thăn Ngoại Sốt Teriyaki & Cơm Bơ', 159000, 'cat_sangtao',
   'Xiên thăn ngoại bò sốt Teriyaki ăn cùng cơm bơ và trứng chiên kiểu Pháp.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577535/Steak_mini_thanbongoaisotteriyaki_o2p0dz.png', true),

  ('item_pasta_bo', 'Mỳ Ý Sốt Bò Bằm', 129000, 'cat_pasta',
   'Mỳ Ý sốt bò bằm đậm vị, phù hợp cho bữa trưa hoặc món dùng chung.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577555/myysotbobam_eggdgv.png', true),
  ('item_pasta_nam', 'Mỳ Ý Sốt Kem Nấm', 129000, 'cat_pasta',
   'Mỳ Ý sốt kem nấm béo nhẹ, thơm vị nấm áp chảo.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577557/myysotkemnam_aprdvp.png', true),
  ('item_pasta_cahoi', 'Mỳ Ý Cá Hồi & Mực Sốt Tomyum', 149000, 'cat_pasta',
   'Mỳ Ý cá hồi và mực dùng cùng sốt Tomyum chua cay.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577554/myycahoi_mucsottomyum_de8mjy.png', true),

  ('item_pizza_bo', 'Pizza Bò Bằm', 159000, 'cat_pizza',
   'Pizza bò bằm đế mỏng, phô mai kéo sợi và sốt cà chua đậm vị.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577553/pizzabobam_ddaskl.png', true),
  ('item_pizza_dua', 'Pizza Dứa Xúc Xích', 159000, 'cat_pizza',
   'Pizza dứa, xúc xích và phô mai nướng vàng.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577552/pizzaduaxucxich_ojdwik.png', true),
  ('item_pizza_ga', 'Pizza Gập Nhân Phô Mai Bò Bằm', 159000, 'cat_pizza',
   'Pizza gập nhân phô mai bò bằm, phù hợp dùng chung.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577554/pizzagapnhanphomaibobam_q7i0tq.png', true),

  ('item_caesar', 'Salad Caesar', 89000, 'cat_salad',
   'Salad Caesar tươi nhẹ với sốt đặc trưng.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577560/saladcaesar_svc0h3.png', true),
  ('item_bistrosalad', 'Salad Bistro Pháp', 119000, 'cat_salad',
   'Salad phong cách bistro Pháp, cân bằng vị béo và tươi.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577559/saladbistrophap_aoy1v3.png', true),
  ('item_hoaqua', 'Salad Hoa Quả Theo Mùa', 89000, 'cat_salad',
   'Salad hoa quả theo mùa, tươi mát và dễ dùng.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577564/saladhoaquatheomua_efoipa.png', true),
  ('item_nhietdoi', 'Salad Hoa Quả Nhiệt Đới', 99000, 'cat_salad',
   'Salad hoa quả nhiệt đới với vị chua ngọt tự nhiên.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577562/saladhoaquanhietdoi_qlojxu.png', true),
  ('item_luonvitsalad', 'Salad Lườn Vịt Xông Khói', 139000, 'cat_salad',
   'Salad ăn cùng lườn vịt xông khói, phù hợp khai vị.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577558/luonvitxongkhoi_duzzr3.png', true),

  ('item_mangtay', 'Măng Tây & Khoai Tây Bi Áp Chảo', 89000, 'cat_sides',
   'Măng tây và khoai tây bi áp chảo cùng tỏi chiên bơ và phô mai Parmesan.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577569/mangtay_khoaitaybiapchao_wnd7iy.png', true),
  ('item_nammo', 'Nấm Mỡ & Măng Tây Áp Chảo', 89000, 'cat_sides',
   'Nấm mỡ và măng tây áp chảo sốt Teri cùng phô mai Parmesan.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577569/nammo_mangtayapchao_j6jsu3.png', true),

  ('item_kidcombo', 'Kid Combo & Cơm Phô Mai Bò Bằm', 99000, 'cat_do_chien',
   'Combo cho trẻ em với cơm phô mai bò bằm.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577534/kidcombo_comphomaibobam_zqlbm2.png', true),
  ('item_ga_chien', 'Gà Chiên Đặc Biệt', 99000, 'cat_do_chien',
   'Gà chiên đặc biệt giòn nóng, dễ dùng chung.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577534/gachiendacbiet_hfzxye.png', true),
  ('item_dia_chien', 'Đĩa Chiên Tổng Hợp', 199000, 'cat_do_chien',
   'Đĩa chiên tổng hợp phù hợp gọi cho cả bàn.',
   'https://res.cloudinary.com/ducj0zvys/image/upload/v1781577533/diachientonghop_r6tuqh.png', true)
on conflict ("id") do update set
  "name" = excluded."name",
  "price" = excluded."price",
  "categoryId" = excluded."categoryId",
  "description" = excluded."description",
  "image" = excluded."image",
  "isActive" = excluded."isActive";
